version: "3"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ../nginx/certs:/etc/nginx/certs
    networks:
      - selenium  

  firefox:
    image: selenium/standalone-firefox-debug:3.13.0
    container_name: firefox
    ports:
      - "4444:4444"
      - "5900:5900"
    volumes:
      - "/dev/shm:/dev/shm"
    networks:
      - selenium
  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - ../data/db:/data/db
    command: mongod
    networks:
       - selenium
    env_file:
      - ../config/.env
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: web
    working_dir: /web
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=predictcs.computing.dcu.ie
    volumes:
       - "../:/web"
    command: "python /web/src/app.py"
    networks:
       - selenium
    depends_on:
       - mongo
    env_file:
      - ../config/.env
  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: bot
    working_dir: /coderbot
    environment:
       - SELENIUM=http://firefox:4444/wd/hub
    volumes:
       - "../:/coderbot"
    command: "tail -f /dev/null" #"python /coderbot/src/talk.py"
    networks:
       - selenium
    depends_on:
       - firefox
       - mongo
       - web
    env_file:
      - ../config/.env

networks:
  selenium:
