version: "3"

services:

  firefox:
    image: selenium/standalone-firefox-debug:3.13.0
    container_name: firefox
    ports:
      - "4444:4444"
      - "5900:5900"
    volumes:
      - "/dev/shm:/dev/shm"
    networks:
      - selenium

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: bot
    working_dir: /coderbot
    environment:
       - SELENIUM=http://firefox:4444/wd/hub
    volumes:
       - "../:/coderbot"
    command: "python src/talk.py"
    networks:
       - selenium
    depends_on:
       - firefox
    env_file:
      - ../config/.env

networks:
  selenium:
